# Generated by Django 4.2.17 on 2025-02-09 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_chatmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
