# Generated by Django 4.2.17 on 2025-06-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="encrypted_message_for_receiver",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="encrypted_message_for_sender",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_encrypted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
