# Generated by Django 4.2.17 on 2025-01-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0004_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="blogimage",
            field=models.ImageField(blank=True, null=True, upload_to="blogimages/"),
        ),
    ]
